apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
  labels:
    app: devops-demo
spec:
  selector:
    app: devops-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
